name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - master
      - main
    paths:
      - 'docs/**'
      - 'lib/**'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.5'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: |
          flutter pub get
          cd docs
          flutter pub get

      - name: Build Flutter Web
        run: |
          cd docs
          flutter build web --release --base-href /flutter_mcon/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/web

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
